name: Code style checks

on:
  push:
    branches:
      - "master"
  create:
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  black:
    name: Check black compliance.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Black
        uses: psf/black@stable
        with:
          options: "--config pyproject.toml --check"
          src: "."

  docstring:
    name: Check docstring compliance.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Interrogate
        uses: JackMcKew/python-interrogate-check@main
